In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from pprint import pprint

In [2]:
train_df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")
train_labels = train_df.pop('target')
test_labels = test_df.pop('target')
train_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     61    1   4       138   166    0        2      125      1      3.6   
1     58    1   2       120   284    0        2      160      0      1.8   
2     57    1   4       110   201    0        0      126      1      1.5   
3     46    0   4       138   243    0        2      152      1      0.0   
4     44    1   4       120   169    0        0      144      1      2.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
235   53    0   4       130   264    0        2      143      0      0.4   
236   54    1   4       122   286    0        2      116      1      3.2   
237   67    1   4       160   286    0        2      108      1      1.5   
238   44    1   3       140   235    0        2      180      0      0.0   
239   52    1   4       112   230    0        0      160      0      0.0   

     slope  ca    thal  
0        2   1  normal  
1        2   0  normal  
2        2   0   fixed  
3        2   0  normal  
4        3   0   fixed  
..     ...  ..     ...  
235      2   0  normal  
236      2   2  normal  
237      2   3  normal  
238      1   0  normal  
239      1   1  normal  

[240 rows x 13 columns]

In [3]:
def create_model():
    input1 = tf.keras.Input(shape=(13,))
    hidden1 = tf.keras.layers.Dense(units = 12, activation='relu')(input1)
    hidden2 = tf.keras.layers.Dense(units = 6, activation='relu')(hidden1)
    output1 = tf.keras.layers.Dense(units = 2, activation='softmax')(hidden2)
    
    model = tf.keras.models.Model(inputs = input1, outputs = output1, name= "functional1")
    
    
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [4]:
def show_dataset(ds):
    for element in dataset:
        pprint(element)
        print('-----')

def show_batch(dataset):
    for batch, label in dataset.take(1):
        print("{:20s}: {}".format('labels',label))
        for key, value in batch.items():
            print("{:20s}: {}".format(key,value.numpy()))
    

In [5]:
#Single list
dataset = tf.data.Dataset.from_tensor_slices([1,2,3])
show_dataset(dataset)

<tf.Tensor: shape=(), dtype=int32, numpy=1>
-----
<tf.Tensor: shape=(), dtype=int32, numpy=2>
-----
<tf.Tensor: shape=(), dtype=int32, numpy=3>
-----


In [6]:
# List of list
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4]])
show_dataset(dataset)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>
-----
<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>
-----


In [7]:
# Tuple of list
dataset = tf.data.Dataset.from_tensor_slices(([1,2],[3,4]))
show_dataset(dataset)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)
-----
(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)
-----


In [8]:
dataset = tf.data.Dataset.from_tensor_slices({"a": [1, 2], "b": [3, 4]})
show_dataset(dataset)

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 'b': <tf.Tensor: shape=(), dtype=int32, numpy=3>}
-----
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 'b': <tf.Tensor: shape=(), dtype=int32, numpy=4>}
-----


In [9]:
t_array = np.random.uniform(size=(4,4))
t_label = np.random.uniform(size=(4,))
dataset = tf.data.Dataset.from_tensor_slices((t_array,t_label))
show_dataset(dataset)

(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.19529631, 0.30315162, 0.7516546 , 0.78537981])>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.771112019106497>)
-----
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.0996021 , 0.10828723, 0.03830565, 0.47582157])>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.7702948468663147>)
-----
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.81007576, 0.12840866, 0.21131634, 0.1795869 ])>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.015557314638960595>)
-----
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.52153009, 0.09866341, 0.53271129, 0.85171964])>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.6597498274997844>)
-----


In [10]:
#From text files
dataset = tf.data.TextLineDataset(tf.io.gfile.glob("data/multiple/*.csv"))
dataset
show_dataset(dataset)

<tf.Tensor: shape=(), dtype=string, numpy=b'age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'61,1,4,138,166,0,2,125,1,3.6,2,1,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'58,1,2,120,284,0,2,160,0,1.8,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,4,110,201,0,0,126,1,1.5,2,0,fixed,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'61,1,4,138,166,0,2,125,1,3.6,2,1,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'58,1,2,120,284,0,2,160,0,1.8,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,4,110,201,0,0,126,1,1.5,2,0,fixed,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,0,4,138,243,0,2,152,1,0,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'44,1,4,120,169,0,0,144,1,2.8,3,0,fixed

<tf.Tensor: shape=(), dtype=string, numpy=b'66,1,2,160,246,0,0,120,1,0,2,3,fixed,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'58,1,3,140,211,1,2,165,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'44,1,4,112,290,0,2,153,0,0,1,1,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'59,1,4,110,239,0,2,142,1,1.2,2,1,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'58,1,3,105,240,0,2,154,1,0.6,2,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,1,2,192,283,0,2,195,0,0,1,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'67,1,4,120,237,0,0,71,0,1,2,0,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,0,2,105,204,0,0,172,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,0,130,131,0,1,115,1,1.2,1,1,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,1,4,140,239,0,0,160,0,1.2,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,1,3,140,335,0,0

<tf.Tensor: shape=(), dtype=string, numpy=b'51,0,4,130,305,0,0,142,1,1.2,2,0,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,1,3,140,185,0,2,155,0,3,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,1,4,117,230,1,0,160,1,1.4,1,2,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'44,0,3,108,141,0,0,175,0,0.6,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,1,4,140,311,0,0,120,1,1.8,2,2,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,1,3,125,309,0,0,131,1,1.8,2,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'53,1,4,123,282,0,0,95,1,2,2,2,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'41,1,2,135,203,0,0,132,0,0,2,0,fixed,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,0,1,150,240,0,0,171,0,0.9,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'39,0,3,94,199,0,0,179,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'65,0,4,

<tf.Tensor: shape=(), dtype=string, numpy=b'67,1,4,120,237,0,0,71,0,1,2,0,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,0,2,105,204,0,0,172,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,0,130,131,0,1,115,1,1.2,1,1,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,1,4,140,239,0,0,160,0,1.2,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,1,3,140,335,0,0,158,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'49,0,4,130,269,0,0,163,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'62,0,4,160,164,0,2,145,0,6.2,3,3,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'39,0,3,138,220,0,0,152,0,0,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'55,0,2,135,250,0,2,161,0,1.4,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,4,130,131,0,0,115,1,1.2,2,1,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'50,0,4,110,254,0,2,

<tf.Tensor: shape=(), dtype=string, numpy=b'68,1,3,118,277,0,0,151,0,1,1,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,0,4,158,305,0,2,161,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,0,3,142,177,0,2,160,1,1.4,3,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'51,1,3,110,175,0,0,123,0,0.6,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,1,4,145,212,0,2,132,0,2,2,2,fixed,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'62,0,4,140,394,0,2,157,0,1.2,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'43,0,4,132,341,1,2,136,1,3,2,0,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'58,1,4,114,318,0,1,140,0,4.4,3,3,fixed,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'56,1,4,130,283,1,2,103,1,1.6,3,0,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'41,0,2,126,306,0,0,163,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,1,4,110,206,0

<tf.Tensor: shape=(), dtype=string, numpy=b'56,1,1,120,193,0,2,162,0,1.9,2,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'42,1,2,120,295,0,0,162,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'58,0,1,150,283,1,2,162,0,1,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'62,1,2,120,281,0,2,103,0,1.4,2,1,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'43,1,4,115,303,0,0,181,0,1.2,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'52,0,3,136,196,0,2,169,0,0.1,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'70,1,4,130,322,0,2,109,0,2.4,2,3,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,2,154,232,0,2,164,0,0,1,1,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,1,4,125,258,0,2,141,1,2.8,2,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,1,3,150,232,0,2,165,0,1.6,1,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,1,4

<tf.Tensor: shape=(), dtype=string, numpy=b'63,1,4,140,187,0,2,144,1,4,1,2,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'67,0,3,115,564,0,2,160,0,1.6,2,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'39,1,3,140,321,0,2,182,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'66,0,3,146,278,0,2,152,0,0,2,1,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,1,4,128,263,0,0,105,1,0.2,2,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,1,4,120,246,0,2,96,1,2.2,3,1,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'48,1,2,110,229,0,0,168,0,1,3,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'65,0,3,140,417,1,2,157,0,0.8,1,1,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'47,1,3,130,253,0,0,179,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,3,150,126,1,0,173,0,0.2,1,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,0,2,

<tf.Tensor: shape=(), dtype=string, numpy=b'62,1,2,120,281,0,2,103,0,1.4,2,1,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'43,1,4,115,303,0,0,181,0,1.2,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'52,0,3,136,196,0,2,169,0,0.1,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'70,1,4,130,322,0,2,109,0,2.4,2,3,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,2,154,232,0,2,164,0,0,1,1,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,1,4,125,258,0,2,141,1,2.8,2,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,1,3,150,232,0,2,165,0,1.6,1,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,1,4,120,249,0,2,144,0,0.8,1,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'62,0,4,138,294,1,0,106,0,1.9,2,3,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,1,3,125,273,0,2,152,0,0.5,3,1,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'53

<tf.Tensor: shape=(), dtype=string, numpy=b'56,1,4,132,184,0,2,105,1,2.1,2,1,fixed,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'41,1,3,112,250,0,0,179,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,0,4,130,303,0,0,122,0,2,2,2,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'39,1,4,118,219,0,0,140,0,1.2,2,0,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'69,1,3,140,254,0,2,146,0,2,2,3,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'66,1,4,120,302,0,2,151,0,0.4,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,3,150,168,0,0,174,0,1.6,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'58,0,2,136,319,1,2,152,0,0,1,2,normal,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'59,1,4,135,234,0,0,161,0,0.5,2,0,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'55,0,2,132,342,0,0,166,0,1.2,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'49,1,2,130,26

<tf.Tensor: shape=(), dtype=string, numpy=b'59,1,1,160,273,0,2,125,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'35,0,4,138,183,0,0,182,0,1.4,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'63,0,4,108,269,0,0,169,1,1.8,2,2,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'41,1,2,120,157,0,0,182,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'68,1,3,118,277,0,0,151,0,1,1,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,0,4,158,305,0,2,161,0,0,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,0,3,142,177,0,2,160,1,1.4,3,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'51,1,3,110,175,0,0,123,0,0.6,1,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'64,1,4,145,212,0,2,132,0,2,2,2,fixed,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'62,0,4,140,394,0,2,157,0,1.2,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'43,0,4,132,341,1,2,136,

<tf.Tensor: shape=(), dtype=string, numpy=b'58,1,4,146,218,0,0,105,0,2,2,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'55,0,4,128,205,0,1,130,1,2,2,1,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'48,1,2,130,245,0,2,180,0,0.2,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'54,0,3,110,214,0,0,158,0,1.6,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'57,1,4,152,274,0,0,88,1,1.2,2,1,reversible,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'51,0,4,130,305,0,0,142,1,1.2,2,0,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,1,3,140,185,0,2,155,0,3,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'60,1,4,117,230,1,0,160,1,1.4,1,2,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'44,0,3,108,141,0,0,175,0,0.6,2,0,normal,0'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b'46,1,4,140,311,0,0,120,1,1.8,2,2,reversible,1'>
-----
<tf.Tensor: shape=(), dtype=string, numpy=b

In [11]:
tf.io.gfile.glob("data/multiple/*.csv")

['data\\multiple\\train - Copy (2).csv',
 'data\\multiple\\train - Copy (3).csv',
 'data\\multiple\\train - Copy (4).csv',
 'data\\multiple\\train - Copy (5).csv',
 'data\\multiple\\train - Copy (6).csv',
 'data\\multiple\\train - Copy (7).csv',
 'data\\multiple\\train - Copy (8).csv']

In [12]:
# from csv dataframe
dataset = tf.data.Dataset.from_tensor_slices((dict(train_df),train_labels))
dataset = dataset.batch(32)
show_batch(dataset)

labels              : [1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1]
age                 : [61 58 57 46 44 64 53 71 43 69 45 66 57 51 49 54 53 59 35 63 41 68 60 46
 51 64 62 43 58 56 41 54]
sex                 : [1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 1]
cp                  : [4 2 4 4 4 1 4 4 4 1 2 4 4 4 3 4 3 1 4 4 2 3 4 3 3 4 4 4 4 4 2 4]
trestbps            : [138 120 110 138 120 110 140 112 120 160 130 178 150 140 120 124 130 160
 138 108 120 118 158 142 110 145 140 132 114 130 126 110]
chol                : [166 284 201 243 169 211 203 149 177 234 234 228 276 298 188 266 246 273
 183 269 157 277 305 177 175 212 394 341 318 283 306 206]
fbs                 : [0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0]
restecg             : [2 2 0 2 0 2 2 0 2 2 2 0 2 0 0 2 2 2 0 0 0 0 2 2 0 2 2 2 1 2 0 2]
thalach             : [125 160 126 152 144 144 155 125 120 131 175 165 112 122 139 109 173 125
 182 169 182 151 161 160 123 132 157 1

In [13]:
#FROM MULTIPLE CSV FILES
train_ds = tf.data.experimental.make_csv_dataset(
    tf.io.gfile.glob("data/multiple/*.csv"), 
    batch_size = 10, 
    column_names = None, 
    column_defaults= [0,0,0,0,0.,"a",0],
    label_name='target', 
    select_columns = ['age', 'sex', 'cp', 'trestbps','oldpeak','thal', 'target'],  
    shuffle=True, 
    shuffle_seed=101, 
    
)
train_ds
# show_dataset(train_ds)
show_batch(train_ds)


labels              : [0 0 1 0 0 0 0 0 1 1]
age                 : [60 55 55 51 47 57 59 37 59 67]
sex                 : [0 0 1 0 1 1 1 1 1 1]
cp                  : [1 2 4 3 4 2 4 3 4 4]
trestbps            : [150 132 160 140 110 154 138 130 164 100]
oldpeak             : [0.9 1.2 0.8 1.5 1.  0.  0.  3.5 1.  0.9]
thal                : [b'normal' b'normal' b'reversible' b'normal' b'normal' b'normal' b'normal'
 b'normal' b'fixed' b'normal']


In [14]:
dataset = tf.data.Dataset.from_tensor_slices((dict(train_df),train_labels))
dataset = dataset.batch(batch_size = 10, drop_remainder=False)
dataset = dataset.repeat(3)
dataset = dataset.shuffle(buffer_size = 10000, seed=777, reshuffle_each_iteration=None)
# show_dataset(dataset)
show_batch(dataset)

labels              : [1 0 1 0 1 0 1 0 0 0]
age                 : [51 60 60 44 46 64 53 41 60 39]
sex                 : [0 1 1 0 1 1 1 1 0 0]
cp                  : [4 3 4 3 4 3 4 2 1 3]
trestbps            : [130 140 117 108 140 125 123 135 150  94]
chol                : [305 185 230 141 311 309 282 203 240 199]
fbs                 : [0 0 1 0 0 0 0 0 0 0]
restecg             : [0 2 0 0 0 0 0 0 0 0]
thalach             : [142 155 160 175 120 131  95 132 171 179]
exang               : [1 0 1 0 1 1 1 0 0 0]
oldpeak             : [1.2 3.  1.4 0.6 1.8 1.8 2.  0.  0.9 0. ]
slope               : [2 2 1 2 2 2 2 2 1 1]
ca                  : [0 0 2 0 2 0 2 0 0 0]
thal                : [b'reversible' b'normal' b'reversible' b'normal' b'reversible'
 b'reversible' b'reversible' b'fixed' b'normal' b'normal']


In [15]:
x1 = tf.constant(np.random.randint(50, size =(1000,13)), dtype = tf.float32)
y1 = tf.constant(np.random.randint(2, size =(1000,)), dtype = tf.int32)

train_ds = tf.data.Dataset.from_tensor_slices((x1,y1))
train_ds = train_ds.shuffle(1000, seed =101)
train_ds = train_ds.batch(32)


model = create_model()
model.fit(train_ds, epochs = 10)

Epoch 1/10
32/32 [==============================] - 0s 5ms/step - loss: 6.1718 - accuracy: 0.5330
Epoch 2/10
32/32 [==============================] - 0s 5ms/step - loss: 2.0751 - accuracy: 0.5300
Epoch 3/10
32/32 [==============================] - 0s 5ms/step - loss: 1.0255 - accuracy: 0.5250
Epoch 4/10
32/32 [==============================] - 0s 5ms/step - loss: 0.8095 - accuracy: 0.5320
Epoch 5/10
32/32 [==============================] - 0s 5ms/step - loss: 0.7494 - accuracy: 0.5000
Epoch 6/10
32/32 [==============================] - 0s 5ms/step - loss: 0.7298 - accuracy: 0.4800
Epoch 7/10
32/32 [==============================] - 0s 5ms/step - loss: 0.7203 - accuracy: 0.4880
Epoch 8/10
32/32 [==============================] - 0s 5ms/step - loss: 0.7156 - accuracy: 0.4840
Epoch 9/10
32/32 [==============================] - 0s 5ms/step - loss: 0.7089 - accuracy: 0.4800
Epoch 10/10
32/32 [==============================] - 0s 5ms/step - loss: 0.7063 - accuracy: 0.4910
